//action type list 
export const SIGNINSUCCESS ="SIGNIN";
export const SIGNINERROR="SIGNINERROR";
export const SIGNININCORRECT="SIGNININCORRECT";
export const SIGNOUT="SIGNOUT";
export const GET_ONLINE_USER="GET_ONLINE_USER"
export const GET_CONVERSATION="GET_CONVERSATION"
export const GET_CONV_ERROR="GET_CONV_ERROR"
export const ON_CONV_START="ON_CONV_START"
export const SEND_MESSAGE="SEND_MESSAGE"
export const SEND_MESSAGE_ERROR="SEND_MESSAGE_ERROR"
export const DELETE_CONVERSATION="DELETE_CONVERSATION"
export const GET_TRAFFIC_LOCATION="GET_TRAFFIC_LOCATION"
export const CHANGE_LOCATION_CONFIG="CHANGE_LOCATION_CONFIG"

